### ISSUE TITLE
Can't define own `=` rule that behaves like default

### ISSUE THREAD

**Issue by kasbah** [junegunn/vim-easy-align#55]
Maybe this is more of a help request than an actual issue. I often want to align expressions like this in Haskell.
```haskell
defaultPcbnewFpPoly = PcbnewFpPoly { fpPolyPts   = []
                                   , itemLayer   = FSilkS
                                   , itemWidth = 0.15
                                   }
```

So I tried defining my own `=` rule that only matches the last `=`.

```vim
let g:easy_align_delimiters = {
\  '=': { 'pattern': '.*\zs=',
\         'left_margin': 1, 'right_margin': 1, 'stick_to_left': 0 }
\}
```

But it shifts everything along with the `=`, resulting in something like below and I can't decipher [the default `=`'s regex](https://github.com/junegunn/vim-easy-align/blob/2.9.6/autoload/easy_align.vim#L34) to figure out what it does differently.

```haskell
defaultPcbnewFpPoly = PcbnewFpPoly { fpPolyPts   = []
                                   , itemLayer   = FSilkS
                                     , itemWidth = 0.15
                                   }
```

**Comment by junegunn** [comment]
Note that you can use `-=` to align around the last (`-`) occurrences of `=`. I recommend using it instead of defining a less flexible version that you have in mind.

Having said that, due to the limitation of the internal implementation, `\zs` in pattern is not supported, among a few others. I'm not sure if it's possible to fix it. Anyway, `=\([^=]*$\)\@=` seems to work in this case.

**Comment by kasbah** [comment]
Thanks!

**Comment by junegunn** [comment]
@kasbah FYI, I changed the internals and now `:EasyAlign/.*\zs=/` should work as expected. Seems much simpler than the alternative I suggested above.

**Comment by kasbah** [comment]
Neat! Thanks for your work!
