### ISSUE TITLE
Align on delimeter [

### ISSUE THREAD

**Issue by drobati** [junegunn/vim-easy-align#71]
There may be a way but I didn't see anything immediately obvious in the README, but I would like to delimit on the third opening [ in a list of lists.

Turning this
```python
value = [
    [['a', 'b', 'c'], [0]],
    [['a', 'b'], [1]],
    [['a'], [1]],
    [['a', 'c'], [2]]
]
```

Into this
```python
value = [
    [['a', 'b', 'c'],  [0]],
    [['a', 'b'],       [1]],
    [['a'],            [1]],
    [['a', 'c'],       [2]]
]
```

**Comment by drobati** [comment]
Using <space> or comma obviously won't work for me. :(

**Comment by sablime** [comment]
:EasyAlign 3]

**Comment by junegunn** [comment]
Select the lines and align around the last spaces will do in this case (assuming that you have `ga` mapping; `ga-<space>`) 

However it the pattern gets more complicated the above trick will not work anymore, for example:

```
value = [
    [['a', 'b', 'c'], [0, 0]],
    [['a', 'b'], [1, 1]],
    [['a'], [1, 1]],
    [['a', 'c'], [2, 2]]
]
```

In this case you want to align around the third (`3`) or the last (`-`) occurrence of `[`. And since there's no default rule for `[` unless you defined it yourself, you'll have to use a regular expression. And you also have to adjust the margin. In this kind I find it more straightforward to use `:EasyAlign` command instead of `ga` map (interactive mode).

- `:EasyAlign3/[/r0` or `:EasyAlign-/[/r0`
    - `r0` no right margin after the pattern

**Comment by drobati** [comment]
Thank you @junegunn
