### ISSUE TITLE
Align Quotes (for vim syntax)

### ISSUE THREAD

**Issue by chapati23** [junegunn/vim-easy-align#75]
I think I misunderstand the syntax here. I want to auto-align my init.vim to the quotes
```
set expandtab " use spaces instead of tabs
set tabstop=2           " Render TABs using this many spaces.
set shiftwidth=2        " Indentation amount for < and > commands.
```

The command I've tried in visual-mode, having these 3 lines selected: `:EasyAlign/"/` and `:EasyAlign/\"/`
Both no dice. If I replace the quotes with an equality sign `:EasyAlign/=/` it works as expected.

what am I missing?

**Comment by junegunn** [comment]
That's because delimiters highlighted as comment or string are ignored by default.
- https://github.com/junegunn/vim-easy-align#ignoring-delimiters-in-comments-or-strings
- https://github.com/junegunn/vim-easy-align/blob/master/EXAMPLES.md#aligning-in-line-comments

There are a few ways you can make it work
- Align around the last spaces. Since you seem to prefer the command version: `:EasyAlign-/ /`
- Tell the plugin not to ignore them
    - `:EasyAlign/"/ig[]`
        - Which is a shorthand notation for `:EasyAlign/"/{ 'ignore_groups': [] }`
    - You can permanently set it for all kinds of delimiters with `let g:easy_align_ignore_groups = []`
- Define a custom alignment rule for `"`
    - `let g:easy_align_delimiters = { '"': { 'ignore_groups': [] } }`
    - Then you can do `:EasyAlign"`

**Comment by chapati23** [comment]
thanks, should have rtfm until the end. workaround with the spaces works fine for me :)
